option('enable_asserts', type: 'boolean', value: true, description: 'Enable internal asserts')
option('tests', type: 'boolean', value: false, description: 'Build unit tests')

option('executorch',
  type : 'feature',
  value : 'auto',
  description : 'Enable ExecuTorch integration'
)

option('ncnn',
  type : 'feature',
  value : 'auto',
  description : 'Enable NCNN integration (ops-ncnn)'
)

option('hailort',
  type : 'feature',
  value : 'auto',
  description : 'Enable HailoRT integration (ops-hailort)'
)
