#!/usr/bin/env bash
################################################################
# Copyright (C) 2026 Arm Limited. All rights reserved.
################################################################

set -Eeuo pipefail

if [ $# -lt 1 ] || [ $# -gt 2 ]; then
    echo "Usage: $0 <output-path> [template-path]" >&2
    exit 2
fi

output_path="$1"
template_path="${2:-codex-review/prompts/review.md.in}"
pr_intent_path="$(dirname "${output_path}")/pr-intent.md"

base_ref="${REVIEW_BASE_REF:-origin/main}"
head_ref="${REVIEW_HEAD_REF:-HEAD}"
base_sha="${REVIEW_BASE_SHA:-}"
head_sha="${REVIEW_HEAD_SHA:-}"
repository="${REVIEW_REPOSITORY:-${GITHUB_REPOSITORY:-$(basename "$(git rev-parse --show-toplevel)")}}"
pr_number="${REVIEW_PR_NUMBER:-}"
pr_title="${REVIEW_PR_TITLE:-}"
pr_url="${REVIEW_PR_URL:-}"
pr_body="${REVIEW_PR_BODY:-}"

if [ -z "${head_sha}" ]; then
    head_sha="$(git rev-parse "${head_ref}")"
fi

if [ -z "${base_sha}" ]; then
    base_sha="$(git merge-base "${base_ref}" "${head_ref}")"
fi

mkdir -p "$(dirname "${output_path}")"

normalize_text() {
    printf '%s' "$1" | tr '\n' ' '
}

sanitize_single_line() {
    printf '%s' "$1" |
        tr '\r\n\t' '   ' |
        sed -E 's/[`<>{}|]//g; s/[[:space:]]+/ /g; s/^ //; s/ $//; s/^(.{0,180}).*$/\1/'
}

filter_directive_like_text() {
    local value="$1"
    local lower_value

    lower_value="$(printf '%s' "${value}" | tr '[:upper:]' '[:lower:]')"
    if printf '%s\n' "${lower_value}" |
        grep -Eq '(^|[^[:alnum:]_])(codex|reviewer|prompt|ignore|disregard|suppress|jailbreak|override|finding|findings)([^[:alnum:]_]|$)|system message|developer message|system instruction|developer instruction|review instruction|do not report|dont report'; then
        printf '%s' "(filtered)"
    else
        printf '%s' "${value}"
    fi
}

fill_empty() {
    local value="$1"
    local fallback="$2"

    if [ -n "${value}" ]; then
        printf '%s' "${value}"
    else
        printf '%s' "${fallback}"
    fi
}

repository="$(fill_empty "${repository}" "(not provided)")"
base_ref="$(fill_empty "${base_ref}" "(not provided)")"
base_sha="$(fill_empty "${base_sha}" "(not provided)")"
head_sha="$(fill_empty "${head_sha}" "(not provided)")"
pr_number="$(fill_empty "${pr_number}" "(not a pull request run)")"
pr_title="$(fill_empty "$(filter_directive_like_text "$(sanitize_single_line "$(normalize_text "${pr_title}")")")" "(not provided)")"
pr_url="$(fill_empty "${pr_url}" "(not provided)")"
pr_body="$(fill_empty "${pr_body}" "(not provided)")"

export REVIEW_RENDER_REPOSITORY="${repository}"
export REVIEW_RENDER_BASE_REF="${base_ref}"
export REVIEW_RENDER_BASE_SHA="${base_sha}"
export REVIEW_RENDER_HEAD_SHA="${head_sha}"
export REVIEW_RENDER_PR_NUMBER="${pr_number}"
export REVIEW_RENDER_PR_TITLE="${pr_title}"
export REVIEW_RENDER_PR_URL="${pr_url}"

render_pr_intent_context() {
    local body="$1"

    printf '%s\n' "${body}" | awk '
        BEGIN {
            max_items = 40
            max_chars = 600
            print "# Pull Request Intent Context"
            print ""
            print "Generated by deterministic extraction from selected PR description sections."
            print "This file is not the raw PR body and does not contain reviewer instructions."
            print ""
            print "Schema-Version: 1"
            print "Accepted-Sections: goal, intent, intended changes, change, change summary, scope, behavior changes, testing"
            print "Accepted-Item-Forms: bullets, checklists, numbered lists, paragraphs"
            print "Max-Items: " max_items
            print "Max-Item-Chars: " max_chars
            print ""
            print "## Extracted Intent Items"
        }

        function trim(value) {
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", value)
            return value
        }

        function lower(value) {
            return tolower(value)
        }

        function sanitize(value) {
            gsub(/\r/, "", value)
            gsub(/\t/, " ", value)
            gsub(/[`<>{}|]/, "", value)
            gsub(/[[:space:]]+/, " ", value)
            value = trim(value)
            if (length(value) > max_chars) {
                value = substr(value, 1, max_chars)
            }
            return value
        }

        function heading_text(value) {
            value = trim(value)
            if (value ~ /^#{1,6}[[:space:]]+/) {
                sub(/^#{1,6}[[:space:]]+/, "", value)
                return trim(value)
            }
            if (value ~ /^\*\*[^*]+\*\*[[:space:]]*$/) {
                gsub(/^\*\*|\*\*$/, "", value)
                return trim(value)
            }
            return ""
        }

        function accepted_heading(value) {
            value = lower(sanitize(value))
            gsub(/:$/, "", value)
            return value ~ /^(goal|goals|intent|intended changes|intended behavior|change|changes|change summary|summary of changes|scope|behavior changes|behaviour changes|testing|test plan|validation)$/
        }

        function directive_like(value) {
            value = lower(value)
            return value ~ /(^|[^[:alnum:]_])(codex|reviewer|prompt|ignore|disregard|suppress|jailbreak|override|finding|findings)([^[:alnum:]_]|$)|system message|developer message|system instruction|developer instruction|review instruction|do not report|dont report/
        }

        function emit_item(value) {
            value = sanitize(value)
            if (value == "" || directive_like(value)) {
                filtered++
                return
            }
            if (items >= max_items) {
                truncated = 1
                return
            }
            print "- " value
            items++
        }

        function flush_paragraph() {
            if (paragraph != "") {
                emit_item(paragraph)
                paragraph = ""
            }
        }

        /^```/ {
            flush_paragraph()
            in_code = !in_code
            next
        }

        in_code {
            next
        }

        {
            line = trim($0)
            if (line == "") {
                flush_paragraph()
                next
            }

            heading = heading_text(line)
            if (heading != "") {
                flush_paragraph()
                in_accepted_section = accepted_heading(heading)
                next
            }

            if (!in_accepted_section) {
                next
            }

            if (line ~ /^-[[:space:]]+\[[ xX]\][[:space:]]+/) {
                flush_paragraph()
                sub(/^-[[:space:]]+\[[ xX]\][[:space:]]+/, "", line)
                emit_item(line)
                next
            }

            if (line ~ /^[-*+][[:space:]]+/) {
                flush_paragraph()
                sub(/^[-*+][[:space:]]+/, "", line)
                emit_item(line)
                next
            }

            if (line ~ /^[0-9]+[.)][[:space:]]+/) {
                flush_paragraph()
                sub(/^[0-9]+[.)][[:space:]]+/, "", line)
                emit_item(line)
                next
            }

            if (paragraph == "") {
                paragraph = line
            } else {
                paragraph = paragraph " " line
            }
        }

        END {
            flush_paragraph()
            if (items == 0) {
                print "- (none extracted)"
            }
            print ""
            print "Items-Extracted: " (items + 0)
            print "Items-Filtered: " (filtered + 0)
            print "Items-Truncated: " (truncated ? "true" : "false")
        }
    '
}

render_pr_intent_context "${pr_body}" > "${pr_intent_path}"

escape_sed_replacement() {
    printf '%s' "$1" | sed -e 's/[&|\\]/\\&/g'
}

sed \
    -e "s|@@REPOSITORY@@|$(escape_sed_replacement "${REVIEW_RENDER_REPOSITORY}")|g" \
    -e "s|@@BASE_REF@@|$(escape_sed_replacement "${REVIEW_RENDER_BASE_REF}")|g" \
    -e "s|@@BASE_SHA@@|$(escape_sed_replacement "${REVIEW_RENDER_BASE_SHA}")|g" \
    -e "s|@@HEAD_SHA@@|$(escape_sed_replacement "${REVIEW_RENDER_HEAD_SHA}")|g" \
    -e "s|@@PR_NUMBER@@|$(escape_sed_replacement "${REVIEW_RENDER_PR_NUMBER}")|g" \
    -e "s|@@PR_TITLE@@|$(escape_sed_replacement "${REVIEW_RENDER_PR_TITLE}")|g" \
    -e "s|@@PR_URL@@|$(escape_sed_replacement "${REVIEW_RENDER_PR_URL}")|g" \
    -e "s|@@PR_INTENT_PATH@@|$(escape_sed_replacement "${pr_intent_path}")|g" \
    "${template_path}" > "${output_path}"
