# SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[project]
name = "opk-ci"
version = "0.1.0"
description = "CI and development tools for Open Perception Kit"
authors = [{name = "Arm Limited"}]
requires-python = ">=3.8"
dependencies = [
    "setuptools>=65.0",
    "autopep8==2.3.2",
    "pycodestyle==2.14.0",
    "pre-commit==4.6.2",
    "GitPython==3.1.62",
    "requests==2.34.2",
    "argcomplete==3.7.2",
    "cmake-format==0.6.13",
    "coverage==7.16.1",
    "clang-format==20.1.8",
    "clang-tidy==20.1.0",
    "detect-secrets==1.5.0",
    "mypy==1.16.1",
    "pyflakes==3.4.0",
    "types-PyYAML==6.0.12.20250516",
    "vulture==2.16",
]

[tool.setuptools.packages.find]
where = ["."]

[project.scripts]
opk-ci = "opk_ci:main"
