services:
  pek-docs-base: &pek-docs-base
    extends:
      file: ../compose.base.yaml
      service: pek-common-dev

    network_mode: bridge
    container_name: pek-docs-base
    hostname: pek-docs-base
    build:
      context: ..
      dockerfile: Dockerfile
      target: pek-docs-base

  pek-dev-base: &pek-dev-base
    extends:
      file: ../compose.base.yaml
      service: pek-common-dev

    network_mode: bridge
    container_name: pek-dev-base
    hostname: pek-dev-base
    build:
      context: ..
      dockerfile: Dockerfile
      target: pek-dev-base

  pek-release-with-ut:
    <<: *pek-docs-base
    container_name: pek-release-with-ut
    hostname: pek-release-with-ut
    command: |
      bash -c '
        .devcontainer/setup.sh &&
        .devcontainer/platform_init.sh pek-dev-base &&
        ./scripts/build-elements.sh release true &&
        meson test -C development/build --print-errorlogs
      '

  pek-valgrind-check:
    <<: *pek-docs-base
    container_name: pek-valgrind-check
    hostname: pek-valgrind-check
    command: |
      bash -c '
        .devcontainer/setup.sh &&
        .devcontainer/platform_init.sh pek-dev-base &&
        ./scripts/testing/valgrind/test-elements-with-valgrind.sh clean --pipeline only-onnx-yolo
      '

  pek-quality-check-pull-request:
    <<: *pek-dev-base
    container_name: pek-quality-check-pull-request
    command: |
      bash -c '
        .devcontainer/devsetup.sh &&
        .devcontainer/platform_init.sh pek-dev-base &&
        source /work/tools/.venv/bin/activate &&
        expkits-ci --all-checks --pr-target-branch ${PULL_REQUEST_TARGET_BRANCH}
      '

  pek-quality-check-full:
    <<: *pek-dev-base
    container_name: pek-quality-check-full
    command: |
      bash -c '
        .devcontainer/devsetup.sh &&
        .devcontainer/platform_init.sh pek-dev-base &&
        ./scripts/gen-doc.sh &&
        source /work/tools/.venv/bin/activate &&
        expkits-ci --clang-format-check --python-format-check --cmake-format-check --shell-format-check --license-header-check
      '

  pek-sonar-check:
    extends: 
      file: ../compose.base.yaml
      service: pek-common-dev
    container_name: pek-sonar-check
    hostname: pek-sonar-check
    network_mode: bridge
    build:
      context: ..
      dockerfile: Dockerfile
      target: pek-dev-sonar 
    environment:
      PROJECT_ROOT: /work/development
      BUILD_DIR: /work/development/build
      SONAR_HOST_URL: ${SONAR_HOST_URL}
      SONAR_TOKEN: ${SONAR_TOKEN}
      SONAR_BRANCH: ${SONAR_BRANCH}
      SONAR_QUALITYGATE_WAIT: 
      PR_KEY: ${PR_KEY}
      PR_BRANCH: ${PR_BRANCH}
      PR_BASE: ${PR_BASE} 
    command: |
      bash -c '
        .devcontainer/devsetup.sh &&
        .devcontainer/platform_init.sh pek-dev-base &&
        source /work/tools/.venv/bin/activate &&
        ./scripts/build-elements.sh debug true --extra-setup-args=-Db_coverage=true,--wipe &&
        meson test -C "$$BUILD_DIR" --print-errorlogs &&
        gcovr -r . --sonarqube coverage.xml &&
        sonar-scanner -Dsonar.qualitygate.wait="$${SONAR_QUALITYGATE_WAIT}" \
          -Dsonar.branch.name="$$SONAR_BRANCH"
      '

  pek-sonar-check-release:
    extends: 
      file: ../compose.base.yaml
      service: pek-common-dev
    container_name: pek-sonar-check-release
    hostname: pek-sonar-check-release
    network_mode: bridge
    build:
      context: ..
      dockerfile: Dockerfile
      target: pek-dev-sonar 
    environment:
      PROJECT_ROOT: /work/development
      BUILD_DIR: /work/development/build
      SONAR_HOST_URL: ${SONAR_HOST_URL}
      SONAR_TOKEN: ${SONAR_TOKEN}
      SONAR_BRANCH: ${SONAR_BRANCH}
      SONAR_QUALITYGATE_WAIT: ${SONAR_QUALITYGATE_WAIT}
      BUILD_STRING: ${BUILD_STRING} 
      SONAR_PROJECT_VERSION: ${SONAR_PROJECT_VERSION}
    command: |
      bash -c '
        .devcontainer/devsetup.sh &&
        .devcontainer/platform_init.sh pek-dev-base &&
        source /work/tools/.venv/bin/activate &&
        ./scripts/build-elements.sh debug true --extra-setup-args=-Db_coverage=true,--wipe &&
        meson test -C "$$BUILD_DIR" --print-errorlogs &&
        gcovr -r . --sonarqube coverage.xml &&
        sonar-scanner -Dsonar.qualitygate.wait="$${SONAR_QUALITYGATE_WAIT}" \
          -Dsonar.branch.name="$$SONAR_BRANCH" \
          -Dsonar.projectVersion="$$SONAR_PROJECT_VERSION" \
          -Dsonar.buildString="$$BUILD_STRING"
      '
