version: 2
updates:
  - package-ecosystem: pip
    directories:
      - "/"
      - "/tools/opk-ci"
    groups:
      python-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      python-major:
        group-by: dependency-name
        patterns:
          - "*"
        update-types:
          - major
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/London
    open-pull-requests-limit: 10
    rebase-strategy: disabled
    labels: []
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: docker
    directory: "/platforms/arm/corstone"
    schedule:
      interval: daily
      timezone: Europe/London
    open-pull-requests-limit: 10
    rebase-strategy: disabled
    labels: []
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      timezone: Europe/London
    open-pull-requests-limit: 10
    rebase-strategy: disabled
    labels: []
    commit-message:
      prefix: "chore(deps)"
