version: 2
updates:
  - package-ecosystem: pip
    directories:
      - "/"
      - "/tools/opk-ci"
    groups:
      shared-sdk-tools:
        group-by: dependency-name
        patterns:
          - autopep8
          - pycodestyle
          - clang-format
    schedule:
      interval: daily
      timezone: Europe/London
    open-pull-requests-limit: 10
    rebase-strategy: disabled
    labels:
      - dependencies
      - python
      - run-opk-ci
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: docker
    directory: "/platforms/arm/corstone"
    schedule:
      interval: daily
      timezone: Europe/London
    open-pull-requests-limit: 10
    rebase-strategy: disabled
    labels:
      - dependencies
      - run-opk-ci
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      timezone: Europe/London
    open-pull-requests-limit: 10
    rebase-strategy: disabled
    labels:
      - dependencies
      - github_actions
      - run-opk-ci
    commit-message:
      prefix: "chore(deps)"
