services:
  pek-common: &pek-common
    cap_add:
      - SYS_PTRACE

    security_opt:
      - seccomp:unconfined

    privileged: true

    environment:
      - USERNAME=devgoblin

    env_file:
      - devices.env

    ports:
      - 8000:8000
      - 8080:8080
      - 8001:8001
      - 7001:7001
      - 9999:9999
      - 2222:2222

    stdin_open: true
    tty: true
    restart: unless-stopped

  pek-common-dev: &pek-common-dev
    <<: *pek-common
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/work
      - /run/udev:/run/udev:ro

    environment:
      - WAYLAND_DISPLAY=wayland-0
      - DISPLAY
      - USERNAME=devgoblin
