x-pek-runtime-environment: &pek-runtime-environment
  USERNAME: dev

x-pek-development-environment: &pek-development-environment
  WAYLAND_DISPLAY: wayland-0
  DISPLAY: ${DISPLAY:-}

x-pek-model-image-build: &pek-model-image-build
  context: .
  dockerfile: Dockerfile
  secrets:
    - huggingface_token
  args:
    HF_DOWNLOAD_CACHEBUST: ${HF_DOWNLOAD_CACHEBUST:-}
    MODEL_DOWNLOAD_AUTHENTICATED: "${HF_TOKEN:+true}"

services:
  pek-common: &pek-common
    cap_add:
      - SYS_PTRACE

    security_opt:
      - seccomp:unconfined

    privileged: true

    environment:
      <<: *pek-runtime-environment

    # <agent-review:suppress-begin>
    # The env_file object form (path + required) is a Compose feature, which is available since 2.24 (released on 20.12.2023).
    # We are not supporting older releases.
    env_file:
      - path: devices.env
        required: false
    # <agent-review:suppress-end>

    network_mode: host
    stdin_open: true
    tty: true
    restart: unless-stopped

  pek-common-dev: &pek-common-dev
    <<: *pek-common
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/work
      - /run/udev:/run/udev:ro

    environment:
      <<:
        - *pek-runtime-environment
        - *pek-development-environment

  pek-model-image:
    build: *pek-model-image-build

  pek-common-dev-model-image:
    <<: *pek-common-dev
    build: *pek-model-image-build
