sonar.projectKey=LinuxVisionKitAmp_3PIaCH2mDmayKH
sonar.cfamily.compile-commands=development/build/compile_commands.json
sonar.exclusions=development/subprojects/**/*, development/build/**/*, etc/**/*
sonar.scm.provider=git
sonar.python.version=3.13
sonar.coverageReportPaths=coverage.xml

