#pragma once

#include "amp/Bitmap.h"
#include "amp/Tools.h"
#include "amp/Types.h"
#include <cstddef>
#include <cstdint>
#include <deque>
#include <fmt/core.h>
#include <stdint.h>
#include <string>
#include <variant>
#include <vector>

namespace amp {

struct Perception {

    struct VideoFrame {
        uint64_t uuid = Uuid();
        size_t originalWidth = 0;  // width when the source produced the frame
        size_t originalHeight = 0; // height when the source produced the frame
        size_t sourceCropLeft = 0;
        size_t sourceCropRight = 0;
        size_t sourceCropTop = 0;
        size_t sourceCropBottom = 0;

        size_t letterboxLeft = 0;
        size_t letterboxRight = 0;
        size_t letterboxTop = 0;
        size_t letterboxBottom = 0;
    };

    struct Object {
        uint64_t uuid = Uuid();
        uint64_t parentUuid = 0;
        uint64_t creationTsNs = TsUtcNs();
        float confidence = 0.0f;
        std::string text;
    };

    struct Rect : public Object {
        float x = 0.0f, y = 0.0f, w = 0.0f, h = 0.0f;
        int labelId = -1;
    };

    struct YawPitch : public Object {
        float yaw = 0.0f, pitch = 0.0f;
    };

    struct OcrText : public Object {
        float x = 0.0f, y = 0.0f, w = 0.0f, h = 0.0f;
    };

    struct SegmentationMap : public Object {
        enum class Type { Uint8, Uint32 };
        Type type = Type::Uint8;
        std::vector<uint8_t> pixels;
        size_t width = 0, height = 0;

        void set8(size_t x, size_t y, uint8_t value) {
            assert(type == Type::Uint8);
            pixels[y * width + x] = value;
        }

        uint8_t get8(size_t x, size_t y) const {
            assert(type == Type::Uint8);
            return pixels[y * width + x];
        }

        void realloc(Type type, size_t width, size_t height) {
            size_t size = width * height;
            if (type == Type::Uint32)
                size *= 4;
            pixels.resize(size);

            this->type = type;
            this->width = width;
            this->height = height;
        }
    };

    using Detection = std::variant<Rect, YawPitch, OcrText, SegmentationMap>;

    // all detections generated by ONE inference step
    struct Layer {
        std::string engine, model, tags;
        std::string contentType; // "generic-object", "human-face", "human-figure", "ocr-text",
                                 // "eye-yp"
        std::vector<Detection> detections;
    };

    std::vector<Layer> layers;
};

struct PerceptionTools {

    Perception &perception;

    PerceptionTools(Perception &perception) : perception(perception) {}

    std::vector<Perception::Rect> getAllRectsWithContentType(const std::string &type) const {
        std::vector<Perception::Rect> result;

        for (const auto &layer : perception.layers) {
            if (layer.contentType != type)
                continue;

            for (const auto &det : layer.detections) {
                if (const auto *rect = std::get_if<Perception::Rect>(&det)) {
                    result.push_back(*rect);
                }
            }
        }

        return result;
    }

    std::vector<Perception::Rect> getAllRectsWithContentType(const std::string &type,
                                                             uint64_t uuid) const {
        std::vector<Perception::Rect> result;

        for (const auto &layer : perception.layers) {
            if (layer.contentType != type)
                continue;

            for (const auto &det : layer.detections) {
                if (const auto *rect = std::get_if<Perception::Rect>(&det)) {
                    if (rect->uuid == uuid)
                        result.push_back(*rect);
                }
            }
        }

        return result;
    }

    template <typename T>
    std::vector<T> getAllWithContentTypeByUuid(const std::string &type, uint64_t uuid) const {
        std::vector<T> result;

        for (const auto &layer : perception.layers) {
            if (layer.contentType != type)
                continue;

            for (const auto &det : layer.detections) {
                if (const auto *v = std::get_if<T>(&det)) {
                    fmt::print("{} {}\n", v->uuid, uuid);
                    if (v->uuid == uuid) {
                        result.push_back(*v);
                    }
                }
            }
        }
        return result;
    }

    template <typename T> std::vector<T> getAllWithContentType(const std::string &type) const {
        std::vector<T> result;

        for (const auto &layer : perception.layers) {
            if (layer.contentType != type)
                continue;

            for (const auto &det : layer.detections) {
                if (const auto *v = std::get_if<T>(&det)) {
                    result.push_back(*v);
                }
            }
        }
        return result;
    }
};

} // namespace amp