/*************************************************************
 * Copyright (C) 2025 Arm Limited. All rights reserved.
 *************************************************************/

#pragma once

#include "amp/Bitmap.h"
#include "amp/Tools.h"
#include <cstddef>
#include <cstdint>
#include <fmt/core.h>
#include <stdint.h>
#include <string>
#include <variant>
#include <vector>

namespace amp {

struct Perception {

    // base class for detections
    struct Object {
        uint64_t uuid = Uuid();
        uint64_t parentUuid = 0;
        uint64_t creationTsNs = TsUtcNs();
    };

    // a viedeo frame descriptor, will be parent of vision inference detections
    struct VideoFrame : public Object {
        size_t originalWidth = 0;  // width when the source produced the frame
        size_t originalHeight = 0; // height when the source produced the frame
        size_t sourceCropLeft = 0;
        size_t sourceCropRight = 0;
        size_t sourceCropTop = 0;
        size_t sourceCropBottom = 0;

        size_t letterboxLeft = 0;
        size_t letterboxRight = 0;
        size_t letterboxTop = 0;
        size_t letterboxBottom = 0;
    };

    // a audio data chunk descriptor, will be parent of audio inference detections
    struct AudioFrame : public Object {
        size_t originalChannels = 0;
        size_t originalFrequency = 0;
        size_t originalSampleCount = 0;
        size_t cutLeftSampleCount = 0;
        size_t cutRightSampleCount = 0;
    };

    // detection rectangle
    struct Rect : public Object {
        float x = 0.0f, y = 0.0f, width = 0.0f, height = 0.0f;
        float confidence = 0.0f;
        int classId = -1;
        std::string text;
    };

    // full-crop classification result
    struct Classification : public Object {
        // with classification we store multiple candidates
        struct Candidate {
            float confidence = 0.0f;
            int classId = -1;
            std::string text;
            float x = 0.0f, y = 0.0f, w = 0.0f, h = 0.0f;
        };
        std::vector<Candidate> candidates;
    };

    // yaw/pitch estimation result (e.g. for gaze estimation)
    struct YawPitch : public Object {
        float confidence = 0.0f;
        float yaw = 0.0f, pitch = 0.0f;
    };

    // localized text result (e.g. for OCR detection)
    struct LocalizedText : public Object {
        float x = 0.0f, y = 0.0f, w = 0.0f, h = 0.0f;
        std::string text;
    };

    // segmentation map result (e.g. for OCR detection)
    struct SegmentationMap : public Object {
        amp::Bitmap bitmap;
    };

    // track history trace (e.g. fading trail for tracked objects)
    struct TrackTrace : public Object {
        struct Point {
            float x = 0.0f;
            float y = 0.0f;
        };

        uint64_t trackId = 0;
        std::vector<Point> points;
    };

    // object embedding vector (e.g. ReID descriptor) linked to a parent detection
    struct ObjectEmbedding : public Object {
        std::vector<float> values;
    };

    // one detection instance
    using Detection = std::variant<Rect,
                                   YawPitch,
                                   LocalizedText,
                                   SegmentationMap,
                                   TrackTrace,
                                   ObjectEmbedding,
                                   VideoFrame,
                                   Classification,
                                   AudioFrame>;

    // all detections generated by ONE inference step
    struct Layer {
        std::string engine;
        std::string model;
        std::string tags;
        std::string inferElementId;

        // possible values:
        // "coco"
        // "imageNet"
        std::string labelFamily;

        // possible values:
        // "genericObject"
        // "humanFace"
        // "humanFigure"
        // "segmentation"
        // "eyeYawPitch"
        // "classification"
        // "personClassification"
        // "trackTrace"
        std::string contentType;

        // Optional OSD/rendering hint for the layer.
        // Examples:
        // "overlay"
        // "backgroundReplacement"
        std::string compositingMode;

        std::vector<Perception::Detection> detections;
    };

    std::vector<std::string> perfdata;
    std::vector<Layer> layers;
};

template <class P> struct PerceptionToolsBase {
    P &perception;

    explicit PerceptionToolsBase(P &p) : perception(p) {}

    // ---- your existing methods can stay as-is (they only read) ----
    std::vector<Perception::Rect> getAllRectsWithContentType(const std::string &type) const {
        std::vector<Perception::Rect> result;

        for (const auto &layer : perception.layers) {
            if (layer.contentType != type)
                continue;

            for (const auto &det : layer.detections) {
                if (const auto *rect = std::get_if<Perception::Rect>(&det)) {
                    result.push_back(*rect);
                }
            }
        }
        return result;
    }

    std::vector<Perception::Rect> getAllRectsWithContentType(const std::string &type,
                                                             uint64_t uuid) const {
        std::vector<Perception::Rect> result;

        for (const auto &layer : perception.layers) {
            if (layer.contentType != type)
                continue;

            for (const auto &det : layer.detections) {
                if (const auto *rect = std::get_if<Perception::Rect>(&det)) {
                    if (rect->uuid == uuid)
                        result.push_back(*rect);
                }
            }
        }
        return result;
    }

    template <typename T>
    std::vector<T> getAllWithContentTypeByUuid(const std::string &type, uint64_t uuid) const {
        std::vector<T> result;

        for (const auto &layer : perception.layers) {
            if (layer.contentType != type)
                continue;

            for (const auto &det : layer.detections) {
                if (const auto *v = std::get_if<T>(&det)) {
                    if (v->uuid == uuid)
                        result.push_back(*v);
                }
            }
        }
        return result;
    }

    template <typename T> std::vector<T> getAllWithContentType(const std::string &type) const {
        std::vector<T> result;

        for (const auto &layer : perception.layers) {
            if (layer.contentType != type)
                continue;

            for (const auto &det : layer.detections) {
                if (const auto *v = std::get_if<T>(&det)) {
                    result.push_back(*v);
                }
            }
        }
        return result;
    }

    // ---- example of a mutating method only available when P is non-const ----
    void clearLayers()
        requires(!std::is_const_v<P>)
    {
        perception.layers.clear();
    }

    // or return non-const refs, etc, only in the non-const wrapper
    auto &layers()
        requires(!std::is_const_v<P>)
    {
        return perception.layers;
    }
};

// convenient aliases:
using PerceptionTools = PerceptionToolsBase<Perception>;
using ConstPerceptionTools = PerceptionToolsBase<const Perception>;

} // namespace amp
