@startuml
!include amp-style.puml

title AMP Engine Independent Inference Overview

skinparam package<<inference-container>> {
  BackgroundColor transparent
  BorderColor transparent
  StereotypeFontColor transparent
}

package " " <<inference-container>>{
    package "AMP-Model representation\n\nAPI agnostic generic model descriptor\n- input/output formats\n- pre/post-processor types\n- inference configs" as AMPModel
    package "Inference" as Inference {
    together {
        component "ONNX Runtime" as ONNX
        component "HailoRT" as HAILO
        component "ExecuTorch" as EXEC
    }

    ONNX -[hidden]right-> HAILO
    HAILO -[hidden]right-> EXEC
    }

    package "Inference result metadata\n\nSimple user friendly outputs:\n- bounding boxes\n- text\n- scalars\n- etc." as ResultMeta

    rectangle "ONNX runtime resource\n(.onnx file)" as ResOnnx
    rectangle "HailoRT resource\n(.hef file)" as ResHef
    rectangle "ExecuTorch resource\n(.pte file)" as ResPte

    ResOnnx -[hidden]right-> ResHef
    ResHef -[hidden]right-> ResPte

    ResOnnx -[dashed]-> AMPModel : represented as\n(config: ONNX)
    ResHef  -[dashed]-> AMPModel : represented as\n(config: HailoRT)
    ResPte  -[dashed]-> AMPModel : represented as\n(config: ExecuTorch)

    AMPModel -down[hidden]-> Inference
    AMPModel -down-> Inference : model description\n& inference config

    Inference -down[hidden]-> ResultMeta
    Inference -down-> ResultMeta : produces
}
@enduml
