@startuml
!include amp-style.puml

title WebRTC media and control flow

participant "Host Web Browser" as Browser
participant "Container" as Container
participant "AmpSource" as AmpSource
participant "Ampsink" as Ampsink

Browser -> Container : Webcam/Mic
activate Container
Container -> AmpSource : Deliver media stream

Browser -> Container : REST control commands
Container -> Ampsink : Handle control command

Container --> Browser : Control response
deactivate Container

@enduml