# SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

export ZSH="${HOME}/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)
[[ -f "${ZSH}/oh-my-zsh.sh" ]] && source "${ZSH}/oh-my-zsh.sh"

if [[ -o interactive ]]; then
  if [[ -z "${VIRTUAL_ENV:-}" && -f /work/tools/.venv/bin/activate ]]; then
    source /work/tools/.venv/bin/activate
  fi

  if [[ -f /work/scripts/private/opk-terminal-init.sh ]]; then
    OPK_TERMINAL_INIT_SKIP_BASHRC=1 bash /work/scripts/private/opk-terminal-init.sh
  fi
fi

eval "$(register-python-argcomplete opk-ci)" 2>/dev/null || true
