x-pek-dev-image-build: &pek-dev-image-build
  context: ..
  dockerfile: Dockerfile
  network: ${BUILD_NETWORK_MODE:-default}

x-pek-hailo-build: &pek-hailo-build
  context: ..
  dockerfile: .devcontainer/Dockerfile.hailo
  additional_contexts:
    pek-dev: service:pek-dev

x-pek-huggingface-environment: &pek-huggingface-environment
  HF_TOKEN_PATH: /run/secrets/huggingface_token

x-pek-huggingface-secret: &pek-huggingface-secret
  source: huggingface_token
  target: /run/secrets/huggingface_token
  uid: "${HOST_UID:-1000}"
  gid: "${HOST_GID:-1000}"
  mode: 0400

services:
  pek-build-base:
    image: ${PEK_BUILD_BASE_IMAGE:-perception-experience-kit-build-base}
    build:
      context: ..
      dockerfile: Dockerfile
      target: pek-build-base

  pek-dev:
    extends:
      file: ../compose.base.yaml
      service: pek-common-dev
    environment:
      <<: *pek-huggingface-environment
    secrets:
      - *pek-huggingface-secret
    container_name: ${PEK_DEV_CONTAINER_NAME:-perception-experience-kit}
    hostname: ${PEK_DEV_CONTAINER_NAME:-perception-experience-kit}
    command: sleep infinity
    build:
      <<: *pek-dev-image-build
      target: pek-dev
      args:
        USER_UID: ${HOST_UID:-1000}
        USER_GID: ${HOST_GID:-1000}
        PEK_PICAMERA: ${PEK_PICAMERA:-disabled}
        EXECUTORCH_ARTIFACTORY_USERNAME: ${EXECUTORCH_ARTIFACTORY_USERNAME:-}
        EXECUTORCH_ARTIFACTORY_PASSWORD: ${EXECUTORCH_ARTIFACTORY_PASSWORD:-}
        EXECUTORCH_VERSION: ${EXECUTORCH_VERSION:-}
        EXECUTORCH_DEB_REVISION: ${EXECUTORCH_DEB_REVISION:-}
    volumes:
      - ${SSH_AUTH_SOCK:-/dev/null}:/ssh-agent

  pek-dev-rpi5-h8:
    extends:
      file: ../compose.base.yaml
      service: pek-common-dev
    environment:
      <<: *pek-huggingface-environment
    secrets:
      - *pek-huggingface-secret
    container_name: ${PEK_DEV_RPI5_H8_CONTAINER_NAME:-perception-experience-kit-rpi5-h8}
    hostname: ${PEK_DEV_RPI5_H8_CONTAINER_NAME:-perception-experience-kit-rpi5-h8}
    command: sleep infinity
    build:
      <<: *pek-hailo-build
      args:
        PEK_HAILO_ARCH: h8
    volumes:
      - ${SSH_AUTH_SOCK:-/dev/null}:/ssh-agent

  pek-dev-rpi5-h10:
    extends:
      file: ../compose.base.yaml
      service: pek-common-dev
    environment:
      <<: *pek-huggingface-environment
    secrets:
      - *pek-huggingface-secret
    container_name: ${PEK_DEV_RPI5_H10_CONTAINER_NAME:-perception-experience-kit-rpi5-h10}
    hostname: ${PEK_DEV_RPI5_H10_CONTAINER_NAME:-perception-experience-kit-rpi5-h10}
    command: sleep infinity
    build:
      <<: *pek-hailo-build
      args:
        PEK_HAILO_ARCH: h10
    volumes:
      - ${SSH_AUTH_SOCK:-/dev/null}:/ssh-agent
secrets:
  huggingface_token:
    environment: HF_TOKEN
