# SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
  opk-build-base:
    profiles: [build]
    image: ${OPK_BUILD_BASE_IMAGE:-open-perception-kit-build-base}
    build:
      context: ..
      dockerfile: Dockerfile
      target: opk-build-base

  opk-dev:
    extends:
      file: ../compose.base.yaml
      service: opk-common-dev-model-image
    image: ${OPK_DEV_IMAGE:-open-perception-kit-dev}
    container_name: ${OPK_DEV_CONTAINER_NAME:-open-perception-kit}
    hostname: ${OPK_DEV_CONTAINER_NAME:-open-perception-kit}
    extra_hosts:
      - "${OPK_DEV_CONTAINER_NAME:-open-perception-kit}:127.0.0.1"
    command: sleep infinity
    build:
      network: ${BUILD_NETWORK_MODE:-default}
      target: opk-dev
      secrets:
        - executorch_artifactory_username
        - executorch_artifactory_password
      args:
        USER_UID: ${HOST_UID:-1000}
        USER_GID: ${HOST_GID:-1000}
        OPK_PICAMERA: ${OPK_PICAMERA:-disabled}
        EXECUTORCH_VERSION: ${EXECUTORCH_VERSION:-}
        EXECUTORCH_DEB_REVISION: ${EXECUTORCH_DEB_REVISION:-}
secrets:
  huggingface_token:
    environment: HF_TOKEN
  executorch_artifactory_username:
    environment: EXECUTORCH_ARTIFACTORY_USERNAME
  executorch_artifactory_password:
    environment: EXECUTORCH_ARTIFACTORY_PASSWORD
