name: pek-rich

services:
  pek-dev-rich:
    extends:
      file: ../compose.base.yaml
      service: pek-common-dev
    image: pek-dev-rich:local
    container_name: ${PEK_RICH_CONTAINER_NAME:-pek-dev-rich}
    hostname: pek
    user: "0:0"
    command:
      - /usr/local/bin/pek-rich-start
    build:
      context: ..
      dockerfile: .devcontainer/rich/Dockerfile
      target: pek-dev-rich
      additional_contexts:
        pek-dev: service:pek-dev
    environment:
      USERNAME: dev
      HOST_UID: ${HOST_UID:-1000}
      HOST_GID: ${HOST_GID:-1000}
      XDG_RUNTIME_DIR: /run/user/${HOST_UID:-1000}
      PEKCOMM_FILE: /tmp/pekcomm
    volumes:
      - ${PEK_RICH_RUNTIME_DIR:-/tmp}:/run/user/${HOST_UID:-1000}
      - ${PEK_RICH_CONFIGS_MOUNT:-pek-rich-configs}:/home/dev/configs
      - ${PEK_RICH_WORK_TREE_MOUNT:-pek-rich-work-tree}:/pek-work-tree
      - ${SSH_AUTH_SOCK:-/dev/null}:/ssh-agent
volumes:
  pek-rich-configs:
  pek-rich-work-tree:
