services:
  pek-dev:
    user: root
    build:
      cache_from:
        - ${PEK_DEV_CACHE_FROM:-type=registry,ref=ghcr.io/arm-debug/amp-dev-forge-dev:buildcache}
    environment:
      HOST_UID: ${HOST_UID}
      HOST_GID: ${HOST_GID}
    volumes:
      - ccache:/work/.cache/ccache
      - build-output:/work/development/build

volumes:
  ccache:
  build-output:
