# SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
  coturn:
    extends:
      file: docker-compose.devcont.turn.yaml
      service: coturn

  opk-dev-rich:
    network_mode: bridge
    ports:
      - "8000:8000"
      - "8080:8080"
      - "8001:8001"
      - "8002:8002"
      - "7001:7001"
      - "9999:9999"
      - "2222:2222"
    depends_on:
      - coturn
    environment:
      WEBRTC_HOST_IP: ${WEBRTC_HOST_IP}
      OPK_WEBRTC_TURN_USERNAME: ${OPK_WEBRTC_TURN_USERNAME:-test}
      OPK_WEBRTC_TURN_CREDENTIAL: ${OPK_WEBRTC_TURN_CREDENTIAL:-test123}
      OPK_WEBRTC_TURN_MIN_PORT: ${OPK_WEBRTC_TURN_MIN_PORT:-49000}
      OPK_WEBRTC_TURN_MAX_PORT: ${OPK_WEBRTC_TURN_MAX_PORT:-49050}
