# SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates

services:
  opk-dev:
    user: root
    build:
      target: opk-dev-macos-ci
      cache_from:
        - ${OPK_DEV_CACHE_FROM:-type=registry,ref=ghcr.io/arm/open-perception-kit-dev:buildcache}
    environment:
      HOST_UID: ${HOST_UID}
      HOST_GID: ${HOST_GID}
    volumes:
      - ccache:/work/.cache/ccache
      - build-output:/work/development/build

volumes:
  ccache:
  build-output:
