# Copyright (C) 2026 Arm Limited. All rights reserved.

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES PEK_EXECUTORCH_ARM_C_COMPILER PEK_EXECUTORCH_ARM_CXX_COMPILER PEK_EXECUTORCH_ARM_AR PEK_EXECUTORCH_ARM_RANLIB PEK_EXECUTORCH_ARM_STRIP)

foreach(tool IN ITEMS C_COMPILER CXX_COMPILER AR RANLIB STRIP)
    if(NOT DEFINED PEK_EXECUTORCH_ARM_${tool} OR PEK_EXECUTORCH_ARM_${tool} STREQUAL "")
        message(FATAL_ERROR "PEK_EXECUTORCH_ARM_${tool} is required")
    endif()
endforeach()

set(CMAKE_C_COMPILER
    "${PEK_EXECUTORCH_ARM_C_COMPILER}"
    CACHE FILEPATH "Arm64 C compiler")
set(CMAKE_CXX_COMPILER
    "${PEK_EXECUTORCH_ARM_CXX_COMPILER}"
    CACHE FILEPATH "Arm64 C++ compiler")
set(CMAKE_ASM_COMPILER
    "${PEK_EXECUTORCH_ARM_C_COMPILER}"
    CACHE FILEPATH "Arm64 assembler")
set(CMAKE_AR
    "${PEK_EXECUTORCH_ARM_AR}"
    CACHE FILEPATH "Arm64 archiver")
set(CMAKE_RANLIB
    "${PEK_EXECUTORCH_ARM_RANLIB}"
    CACHE FILEPATH "Arm64 ranlib")
set(CMAKE_STRIP
    "${PEK_EXECUTORCH_ARM_STRIP}"
    CACHE FILEPATH "Arm64 strip tool")

set(CMAKE_C_FLAGS_INIT "-march=armv8-a")
set(CMAKE_CXX_FLAGS_INIT "-march=armv8-a")
set(CMAKE_ASM_FLAGS_INIT "-march=armv8-a")

if(EXISTS "/usr/aarch64-linux-gnu")
    set(CMAKE_FIND_ROOT_PATH "/usr/aarch64-linux-gnu")
    set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
    set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
endif()
