# Copyright (C) 2026 Arm Limited. All rights reserved.

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR armv7l)

list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES PEK_EXECUTORCH_ARM_C_COMPILER PEK_EXECUTORCH_ARM_CXX_COMPILER PEK_EXECUTORCH_ARM_AR PEK_EXECUTORCH_ARM_RANLIB PEK_EXECUTORCH_ARM_STRIP)

foreach(tool IN ITEMS C_COMPILER CXX_COMPILER AR RANLIB STRIP)
    if(NOT DEFINED PEK_EXECUTORCH_ARM_${tool} OR PEK_EXECUTORCH_ARM_${tool} STREQUAL "")
        message(FATAL_ERROR "PEK_EXECUTORCH_ARM_${tool} is required")
    endif()
endforeach()

set(CMAKE_C_COMPILER
    "${PEK_EXECUTORCH_ARM_C_COMPILER}"
    CACHE FILEPATH "ARM C compiler")
set(CMAKE_CXX_COMPILER
    "${PEK_EXECUTORCH_ARM_CXX_COMPILER}"
    CACHE FILEPATH "ARM C++ compiler")
set(CMAKE_ASM_COMPILER
    "${PEK_EXECUTORCH_ARM_C_COMPILER}"
    CACHE FILEPATH "ARM assembler")
set(CMAKE_AR
    "${PEK_EXECUTORCH_ARM_AR}"
    CACHE FILEPATH "ARM archiver")
set(CMAKE_RANLIB
    "${PEK_EXECUTORCH_ARM_RANLIB}"
    CACHE FILEPATH "ARM ranlib")
set(CMAKE_STRIP
    "${PEK_EXECUTORCH_ARM_STRIP}"
    CACHE FILEPATH "ARM strip tool")

# The Debian arm-linux-gnueabi toolchain uses the soft-float calling convention. softfp keeps that ABI while allowing XNNPACK's ARMv7 NEON kernels.
set(_PEK_EXECUTORCH_ARM_FLAGS "-march=armv7-a -mfpu=neon -mfloat-abi=softfp")
set(CMAKE_C_FLAGS_INIT "${_PEK_EXECUTORCH_ARM_FLAGS}")
set(CMAKE_CXX_FLAGS_INIT "${_PEK_EXECUTORCH_ARM_FLAGS}")
set(CMAKE_ASM_FLAGS_INIT "${_PEK_EXECUTORCH_ARM_FLAGS}")

set(CMAKE_FIND_ROOT_PATH "/usr/arm-linux-gnueabi")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
