# Copyright (C) 2026 Arm Limited. All rights reserved.

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES PEK_EXECUTORCH_X86_64_C_COMPILER PEK_EXECUTORCH_X86_64_CXX_COMPILER PEK_EXECUTORCH_X86_64_AR PEK_EXECUTORCH_X86_64_RANLIB PEK_EXECUTORCH_X86_64_STRIP)

foreach(tool IN ITEMS C_COMPILER CXX_COMPILER AR RANLIB STRIP)
    if(NOT DEFINED PEK_EXECUTORCH_X86_64_${tool} OR PEK_EXECUTORCH_X86_64_${tool} STREQUAL "")
        message(FATAL_ERROR "PEK_EXECUTORCH_X86_64_${tool} is required")
    endif()
endforeach()

set(CMAKE_C_COMPILER
    "${PEK_EXECUTORCH_X86_64_C_COMPILER}"
    CACHE FILEPATH "x86_64 C compiler")
set(CMAKE_CXX_COMPILER
    "${PEK_EXECUTORCH_X86_64_CXX_COMPILER}"
    CACHE FILEPATH "x86_64 C++ compiler")
set(CMAKE_ASM_COMPILER
    "${PEK_EXECUTORCH_X86_64_C_COMPILER}"
    CACHE FILEPATH "x86_64 assembler")
set(CMAKE_AR
    "${PEK_EXECUTORCH_X86_64_AR}"
    CACHE FILEPATH "x86_64 archiver")
set(CMAKE_RANLIB
    "${PEK_EXECUTORCH_X86_64_RANLIB}"
    CACHE FILEPATH "x86_64 ranlib")
set(CMAKE_STRIP
    "${PEK_EXECUTORCH_X86_64_STRIP}"
    CACHE FILEPATH "x86_64 strip tool")

set(CMAKE_C_FLAGS_INIT "-m64")
set(CMAKE_CXX_FLAGS_INIT "-m64")
set(CMAKE_ASM_FLAGS_INIT "-m64")

if(EXISTS "/usr/x86_64-linux-gnu")
    set(CMAKE_FIND_ROOT_PATH "/usr/x86_64-linux-gnu")
    set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
    set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
endif()
