[project]
name = "plumber"
version = "0.1.0"
description = "Automated test system for Perception Experience Kit"
authors = [{name = "Arm Limited"}]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jmespath==1.1.0",
    "numpy==2.4.2",
    "opk-perception-sdk==0.2.1",
    "pillow==12.3.0",
    "pyright==1.1.408"
]

[tool.setuptools.packages.find]
where = ["."]

[project.scripts]
plumber = "plumber:main"
