!$CONTAINER_COLOR = "#51d358"
!$EXECUTABLE_COLOR = "#5882d8"
!$INTERNAL_MODULE_COLOR = "#9356e7"
!$PIPEWIRE_PAD_COLOR = "#ec5c4f"
!$GPRC_COLOR = $INTERNAL_MODULE_COLOR
!$STORE_COLOR = "#d81111"

!$PIPELINE_COLOR = "#FA6800"
!$SCHEMA_COLOR = "#e7e304"
!$MEDIA_COLOR = "#c70000"
!$METADATA_COLOR = "#1400c7"
!$CONTRACT_COLOR = "#000000"
