@startuml
!include pek-style.puml

title Perception Experience Kit Engine Independent Inference Overview

skinparam package<<inference-container>> {
  BackgroundColor transparent
  BorderColor transparent
  StereotypeFontColor transparent
}

package " " <<inference-container>>{
    package "Perception Experience Kit model representation\n\nAPI agnostic generic model descriptor\n- input/output formats\n- pre/post-processor types\n- inference configs" as PEKModel
    package "Inference" as Inference {
    together {
        component "ONNX Runtime" as ONNX
        component "ExecuTorch" as EXEC
    }

    ONNX -[hidden]right-> EXEC
    }

    package "Inference result metadata\n\nSimple user friendly outputs:\n- bounding boxes\n- text\n- scalars\n- etc." as ResultMeta

    rectangle "ONNX runtime resource\n(.onnx file)" as ResOnnx
    rectangle "ExecuTorch resource\n(.pte file)" as ResPte

    ResOnnx -[hidden]right-> ResPte

    ResOnnx -[dashed]-> PEKModel : represented as\n(config: ONNX)
    ResPte  -[dashed]-> PEKModel : represented as\n(config: ExecuTorch)

    PEKModel -down[hidden]-> Inference
    PEKModel -down-> Inference

    Inference -down[hidden]-> ResultMeta
    Inference -down-> ResultMeta : produces
}
@enduml
