' SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <perception-fdbck@arm.com>
' SPDX-License-Identifier: Apache-2.0
'
' Licensed under the Apache License, Version 2.0 (the "License");
' you may not use this file except in compliance with the License.
' You may obtain a copy of the License at
'
'     https://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing, software
' distributed under the License is distributed on an "AS IS" BASIS,
' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
' See the License for the specific language governing permissions and
' limitations under the License.

@startuml
!include opk-style.puml

title Perception Context Example

start

:Video Sources;

:Yolo object detector inference;
note right
	Attach Object rectangles and labels to perception.
end note

:UltraFace face detector inference;
note right
	Attach Human face rectangles to perception.
end note

:Tracker;
note right
	Attach EntityId to perception.
end note

:Face recognition inference;
note right
	Attach PersonId to perception.
end note

:Messaging;
note right
	Final perception with:
    Object rectangles and labels,
    Human face rectangles,
    EntityId,
    PersonId.
end note

stop
@enduml
