# SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates

[binaries]
c = 'aarch64-linux-gnu-gcc'
cpp = 'aarch64-linux-gnu-g++'
ar = 'aarch64-linux-gnu-gcc-ar'
strip = 'aarch64-linux-gnu-strip'
pkg-config = ['env', 'PKG_CONFIG_LIBDIR=/opt/opk-sysroots/arm64/usr/lib/aarch64-linux-gnu/pkgconfig:/opt/opk-sysroots/arm64/usr/share/pkgconfig', 'PKG_CONFIG_SYSROOT_DIR=/opt/opk-sysroots/arm64', 'pkg-config'] # pragma: allowlist secret

[host_machine]
system = 'linux'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'

[built-in options]
c_args = ['--sysroot=/opt/opk-sysroots/arm64', '-I/opt/opk-sysroots/arm64/usr/include/aarch64-linux-gnu']
cpp_args = ['--sysroot=/opt/opk-sysroots/arm64', '-I/opt/opk-sysroots/arm64/usr/include/aarch64-linux-gnu']
c_link_args = ['--sysroot=/opt/opk-sysroots/arm64']
cpp_link_args = ['--sysroot=/opt/opk-sysroots/arm64']

[properties]
needs_exe_wrapper = true
opk_onnxruntime_root = '/opt/opk-deps/onnxruntime-arm64'
