include "common.fbs";

namespace open_perception_kit.metadata;

table ClassificationCandidate {
  confidence:float;
  class_id:int = -1;
  text:string;
  x:float;
  y:float;
  w:float;
  h:float;
}

table Classification {
  object:open_perception_kit.metadata.ObjectMeta;
  candidates:[open_perception_kit.metadata.ClassificationCandidate];
}

table PersonPresence {
  object:open_perception_kit.metadata.ObjectMeta;
  yes_confidence:float;
  no_confidence:float;
}

table Classifications {
  schema_major:ushort = 1;
  schema_minor:ushort = 0;
  layer:open_perception_kit.metadata.LayerInfo;
  classifications:[open_perception_kit.metadata.Classification];
  person_presence:[open_perception_kit.metadata.PersonPresence];
}

root_type Classifications;
file_identifier "CLSF";
