include "common.fbs";

namespace open_perception_kit.metadata;

table ObjectTrack {
  object:open_perception_kit.metadata.ObjectMeta;
  source_id:ulong;
  track_id:ulong;
  box:open_perception_kit.metadata.BoundingBox;
  confidence:float;
  class_id:int = -1;
  text:string;
  diagnostic:string;
  predicted_only:bool;
}

table ObjectTracks {
  schema_major:ushort = 1;
  schema_minor:ushort = 0;
  layer:open_perception_kit.metadata.LayerInfo;
  tracks:[open_perception_kit.metadata.ObjectTrack];
}

root_type ObjectTracks;
file_identifier "TRKS";
