@startuml
!include pek-style.puml

title WebRTC media and control flow

participant "Host Web Browser" as Browser
participant "Container" as Container
participant "PekSource" as PekSource
participant "Peksink" as Peksink

Browser -> Container : Webcam/Mic
activate Container
Container -> PekSource : Deliver media stream

Browser -> Container : REST control commands
Container -> Peksink : Handle control command

Container --> Browser : Control response
deactivate Container

@enduml
