# SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <perception-fdbck@arm.com>
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Hadolint

on:
  pull_request:
  push:
    branches: [main, develop]
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  pull-requests: read

jobs:
  hadolint:
    name: Lint Dockerfiles
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Find relevant changes
        id: changes
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.changed_files < 3000)
        uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d
        with:
          base: ${{ github.event_name == 'push' && github.ref || '' }}
          filters: |
            relevant:
              - '**Dockerfile*'
              - '.hadolint.yaml'
              - '.hadolint.yml'
              - '.github/workflows/hadolint.yml'

      - name: Lint Dockerfiles
        if: steps.changes.outcome == 'skipped' || steps.changes.outputs.relevant == 'true'
        uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387
        with:
          dockerfile: >-
            Dockerfile
            Dockerfile.pre-commit
            .devcontainer/rich/Dockerfile
