name: Sonar

on:
    workflow_dispatch:
    pull_request:
        branches: [main, "feature/**", "sandbox/**"]
        types: [opened, synchronize, reopened, ready_for_review, labeled]
    schedule:
        - cron: "0 2 * * *" # Every day at 2 AM UTC

jobs:
  build-and-sonar:
    runs-on: self-hosted-ubuntu-latest-x64

    if: |
        (github.event.pull_request.draft == false) ||
        (github.event_name == 'pull_request' && github.event.action == 'labeled' && contains(github.event.label.name, 'run-amp-ci'))

    env:
      DOCKER_COMPOSE_FILE: .github/compose.ci.yaml

    steps:
      - name: Checkout
        uses: actions/checkout@v6
              with:
                  fetch-depth: 0
                  fetch-tags: true
                  ref: ${{ github.head_ref }}

      - name: Build docker image 
        run: docker compose -f ${{ env.DOCKER_COMPOSE_FILE }} build amp-sonar-check
          
      - name: SonarQube analysis
        run: docker compose -f ${{ env.DOCKER_COMPOSE_FILE }} run --rm amp-sonar-check
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
