name: Valgrind Baseline Artifact

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main, "feature/**", "sandbox/**"]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  update-valgrind-baseline:
    name: Generate Valgrind baseline artifact
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    env:
      DOCKER_COMPOSE_FILE: .github/compose.ci.yaml
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Build docker image
        run: docker compose -f ${{ env.DOCKER_COMPOSE_FILE }} build pek-docs-base

      - name: Run Valgrind checks
        id: valgrind_baseline_checks
        continue-on-error: true
        run: docker compose -f ${{ env.DOCKER_COMPOSE_FILE }} run --rm pek-valgrind-check

      - name: Generate Valgrind error summary
        id: valgrind_summary
        if: always()
        run: docker compose -f ${{ env.DOCKER_COMPOSE_FILE }} run --rm pek-generate-valgrind-summary

      - name: Upload Valgrind raw logs # update raw logs for debugging purposes
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: valgrind-baseline-logs
          path: scripts/testing/valgrind/logs
          if-no-files-found: warn
          retention-days: 60

      - name: Upload Valgrind baseline
        if: ${{ github.ref == 'refs/heads/main' && steps.valgrind_summary.outcome == 'success' }}
        uses: actions/upload-artifact@v7
        with:
          name: valgrind-baseline
          path: scripts/testing/valgrind/valgrind-error-summary.xml
          if-no-files-found: warn
          retention-days: 60 # Assume that there will be a commit on the main branch at least every 2 months to keep the baseline available
