
uniflow = static_library(
  'uniflow',                   
  sources: [
    'uniflow.h',
    'uniflow.cpp',
    'tensor_view.h',
    'output_types.h',
    'basic_proc.cpp',
    'basic_proc.h',
    'cpu_kernels.cpp',
    'cpu_kernels.h',
    'internal_types.cpp',
    'internal_types.h',
    'public_types.cpp',
    'public_types.h'
  ],
  include_directories: common_include,
  gnu_symbol_visibility: 'hidden', 
  install: false
)
