
uniflow = static_library(
  'uniflow',                   
  sources: [
    'uniflow.h',
    'uniflow.cpp',
    'tensor_view.h',
    'tensor_types.h',
    'tensor_types.cpp',
    'output_types.h',
    'basic_proc.cpp',
    'basic_proc.h',
    'cpu_imgproc.cpp',
    'cpu_imgproc.h'
  ],
  include_directories: common_include,
  gnu_symbol_visibility: 'hidden', 
  install: false
)
